export const filters = [
  {apiParam: "directorship", model: ref("OPERATIONS"), options: ["OPERATIONS", "NET DEV"], placeholder: "Directorship"},
  {apiParam: "expenditure", model: ref(""), options: ["CAPEX", "OPEX", "OPEX ADM"], placeholder: "Expenditure"},
  {apiParam: "area_sap", model: ref(""), options: ["IT", "NW"], placeholder: "Área SAP"},
  {apiParam: "source_macro", model: ref(""), options: ["TIM", "FIBER"], placeholder: "Source Macro"},
  {apiParam: "agrupamento", model: ref(""), options: ["PROJETO",	"S&M",	"LICENÇAS",	"NGNIS",	"SMART SERVICE (PROJETO)",	"LINHA MIGRADA PARA IT DEV",	"PROFESSIONAL - SERVICE DESK",	"SYSTEM SUPPORT",	"PROFESSIONAL",	"INFRA LOJAS",	"MANUTENÇÃO SWAP FO",	"FISCALIZAÇÃO FMO",	"FATURA B - FMMT",	"FATURA B - PRÉDIOS",	"PRÉDIOS INDUSTRIAIS",	"PRÉDIOS INDUSTRIAIS FMMT (OUTROS)",	"BONIFICAÇÃO FMMT",	"BONIFICAÇÃO FMO",	"PREVENTIVA FMMT",	"CORRETIVA FMMT",	"PREVENTIVA FMO",	"CORRETIVA FMO",	"GMG MENSAL FMMT",	"SOB DEMANDA FMO",	"SOB DEMANDA FMMT",	"CORRETIVA RECORRENTE FMMT",	"FATURA B - GMG FMMT",	"CLIMATIZAÇÃO FMMT",	"PREVENTIVA PERIÓDICA FMMT",	"DAS METRO RJ - FMMT",	"FISCALIZAÇÃO FMMT",	"PLANO VERÃO - FMO",	"DAS METRO SP - FMMT",	"TIM TECH",	"FATURA B - FMMT - VANDALISMO",	"PROTEÇÕES",	"BATERIAS",	"MATERIAL - FIELD",	"MAPA DE RISCO",	"ESTRUTURA VERTICAL",	"VANDALISMO",	"SOBRESSALENTES",	"OUTROS FIELD",	"LIVE",	"POSTOS AVANÇADOS FMMT",	"PROFESSIONAL - SUPPORT",	"REINVESTIMENTO FMMT",	"REINVESTIMENTO FMO",	"AUDITORIA",	"PROFESSIONAL - QUALIDADE",	"RESILIÊNCIA B2B",	"PASSIVO NEGOCIAL",	"REINVESTIMENTO PRÉDIOS INDUSTRIAIS",	"TERMO DE QUITAÇÃO",	"PROFESSIONAL SERVICES"], placeholder: "Agrupamento"},
  {apiParam: "classificacao_pec", model: ref(""), options: ["APP SERVICES","LINHA MIGRADA PARA NW","S&M","LICENÇAS","PROJETO NOVO","SMART SERVICE (PROJETO)","LINHA MIGRADA PARA IT DEV","OBSOLESCÊNCIA","MNGD SERVICES","APLICAÇÃO XAAS","PROFESSIONAL SERVICES","VEGETATIVE GROWTH","LINHA MIGRADA","FIELD MAINTENANCE","RESILIENCE","CONTINUITY","SYSTEM SUPPORT","TRANSFORMATION","LIVE","B2B MOBILE IOT","CONTA ADM",], placeholder: "Classificação P&C"},
  {apiParam: "classificacao_interna", model: ref(""), options: ["APLICAÇÃO XAAS", "APP SERVICES", "AUDITORIA", "BATERIAS", "CONTR. CAMPO (A&F)", "CONTR. CAMPO (TX)", "ESTRUTURA VERTICAL", "FISCALIZAÇÃO", "INFRA LOJAS", "LICENÇAS", "LINHA MIGRADA PARA IT DEV", "LIVE", "MAPA DE RISCO", "MATERIAL - FIELD", "NGNIS", "OUTROS FIELD", "PRÉDIOS H1", "PRÉDIOS INFRA", "PROFESSIONAL SERVICES", "PROJETO", "PROTEÇÕES", "RECLASS VIAGENS", "S&M", "SMART SERVICE (PROJETO)", "SOBRESSALENTES", "SYSTEM SUPPORT", "TERMO DE QUITAÇÃO", "TIM", "TIM TECH", "VANDALISMO"], placeholder: "Classificação Interna"},
  {apiParam: "source", model: ref(""), options: ["B2B", "COZANI", "FIBER", "FIBER ON GOING", "FIBER RESIDENCIAL", "INTELIG", "RURAL", "TIM"], placeholder: "Source"},
  {apiParam: "novo_area_layer", model: ref(""), options: ["Access", "Core", "DSOC", "IBO", "Industrial Building","Infrastructure Planning","NPS","OEM","Office Automation","OSS-A","OSS-S","Transport"], placeholder: "Nova área layer"},
  {apiParam: "novo_layer", model: ref(""), options: ["Access Network Operation","Core Network Operation", "Digital Service Operation Center", "Industrial Building","Infrastructure Planning", "Infrastructure Planning - Gerencial", "Network Protection Solutions","Office Automation", "Operations Support Management", "Transport Network Operation"], placeholder: "Novo layer"},
  {apiParam: "macro_project", model: ref(""), options: ["B2B MOBILE","CONTA ADM","HW MAINTENANCE","IT GROWTH","LINHA MIGRADA PARA IT DEV","METIS - RESILIENCE","NOTEBOOK AS A SERVICE","OTHERS TRANSFORMATION PROJECTS","PROFESSIONAL SERVICES","PROJETO NOVO","RESIDENTIAL BROADBAND","RESILIENCE","S&M","STATUS MAINTENANCE","SW MAINTENANCE"], placeholder: "Macro project"},
  {apiParam: "fornecedor", model: ref(""), options: ["ACCEDIAN","AGT","ALTRAN/ACT","ARSITEC","BINÁRIO","CERAGON","COMFICA","COMTECH","DINA DIGITAL","DIVERSOS","DRUID","ERICSSON","FIBERHOME","FURUKAWA","GILAT","HEADMIND","HPE","HUAWEI","HYPERMATRIX","INFINERA","ITALTEL","ITALTEL/LOGICALIS","MICROFOCUS","NALBATECH","NEC","NOKIA","OSX/VISENT","OTG","PADTEC","PAICON","PROMONLOGICALIS","PROVTEL","REDHAT","SIAE","SIXBELL","SOPHIA","TEL TELECOM","TELCOMANAGER","TELEPERFORMANCE","THALLES","TO BRASIL","WLLCTEL","ZTE"], placeholder: "Fornecedor"},
  {apiParam: "regional", model: ref(""), options: ["TCO","TMG","TNE","TNE 1","TNE 2","TNO","TRJ","TRJ - L1","TRJ - L2","TSL","TSP","TSP - L1","TSP - L2"], placeholder: "Regional"},

]